config/routes.rb
Rails.application.routes.draw do
  get 'user/index'

  get 'user/show'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions' => 'sessions#index'

  root             'test#index'
  get 'about'   => 'test#about'
  get 'contact' => 'test#contact'

  resources :events

  resources :admin
  
  devise_for :admins

  get 'home/index'

  get '/login' => 'sessions#new'
  get '/auth/spotify/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/spotify/consulta' => 'admin#consulta'
  get '/admin/consulta' => 'admin#consulta'

   
  #get 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_from_omniauth(auth_hash)
    self.create(provider: auth_hash[:provider], uid: auth_hash[:uid], name: auth_hash[:uid], scope: 'playlist-read-private user-read-private user-read-email')
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @my_events = Event.where(admin_id: current_admin.id) 
  end

  def new
    @event = Event.new
  end

  def create

  end

  def edit
  end

  def update
  end

  def destroy
  end
  def consulta
      @artists = RSpotify::Artist.search('System of down')
      render json: @artists

  end
  #def show
  #    @artists = RSpotify::Artist.search('System of down')
  #    render json: @artists

  #end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    console
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    if @event.save
      redirect_to admin_index_path
    else
      render :new
    end
  end
  
  def show
    #console
    @event = Event.friendly.find(params[:id])
    @event_artists = @event.artists.split(',')
  
  end

  def all 
    @event =Event.find(:all)
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def event_params
    params.require(:event).permit(:name, :description, :artists, :ticket_link, :admin_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_admin!
  def index
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  helper_method def logged_in?
    !!current_user #double negation to convert to boolean
  end

  helper_method def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] #memoized 
  end

  def new
    redirect_to '/auth/spotify'
  end
  def create
    @user = User.find_by_provider_and_uid(auth_hash[:provider], auth_hash[:uid]) || User.create_from_omniauth(auth_hash)
    if @user
       session[:user_id] = @user.id
       redirect_to root_path
    else
      redirect_to root_url
    end
  end

  def destroy
    reset_session
    redirect_to root_url
  end

  protected
  def auth_hash

    print request.env['omniauth.auth']
    request.env['omniauth.auth']
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  helper_method def logged_in?
    !!current_user #double negation to convert to boolean
  end

  helper_method def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] #memoized
  end

  def new
    redirect_to '/auth/spotify'
  end
  def create
    @user = User.find_by_provider_and_uid(auth_hash[:provider], auth_hash[:uid]) || User.create_from_omniauth(auth_hash)

    @spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    #@spotify_user.create_playlist!('my_awesome_playlist')
    #return render json: @spotify_user.saved_tracks()
    
    @user_artists = @spotify_user.saved_tracks.collect {|song| song.artists[0].name } 
    # session['user_artist'] = @user_artist.to_json
    session[:artists] = @user_artists

    if @user
       session[:user_id] = @user.id
       return redirect_to sessions_path
    else
      return redirect_to sessions_path
    end
  end

  def index
    #console
    @events = Event.all
    @user_artists = session[:artists]
    # puts JSON.parse()session['user_artist']@user_artists
    
    @events_artists = Event.all
    @events_to_go = []
    @events_artists.each do |event|
      @artists_from_events_that_match_user_fav_artists = @user_artists.select do |user_artist|
        if event.artists.split(',').map(&:lstrip).include? user_artist
          @events_to_go << event
        end
      end
    end

    render :template => 'test/index'
  end

  def destroy
    reset_session 
    redirect_to root_url
  end

  protected
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
    helper_method def logged_in?
    !!current_user #double negation to convert to boolean
  end

  helper_method def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id] #memoized
  end

  helper_method def get_event
      @event =Event.all
  end 
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/destroy.html.erb
<h1>Admin#destroy</h1>
<p>Find me in app/views/admin/destroy.html.erb</p>

app/views/admin/edit.html.erb
<h1>Admin#edit</h1>
<p>Find me in app/views/admin/edit.html.erb</p>

app/views/admin/index.html.erb
<h1>Index de Productor Evento</h1>
<!-- <p>Crea y organiza tus eventos.</p>
 -->
<%#= link_to 'Crear Pagina de Evento', new_admin_path %>


<div class="row">
<div class="col-md-12" style="text-align:center;">
<%= link_to 'Crear Pagina de Evento', new_event_path, class: 'btn btn-large btn-primary' %>
</div>
</div>

<h2 style="text-align: left"> Mis eventos </h2>
<ul>
<% if @my_events != nil %>
  <% @my_events.each do |event| %>
    <li>
      <%= link_to event.name, event %>
    </li>
  <% end %>
<% end %>
</ul>

app/views/admin/update.html.erb
<h1>Admin#update</h1>
<p>Find me in app/views/admin/update.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

app/views/events/new.html.erb
<%= bootstrap_form_for(@event, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <%= f.text_field :name, label: "Nombre del Evento:" %>

  <%= f.text_field :description, label: "Descripción evento:" %>

  <%= f.text_field :artists, label: "Artistas que asistirán:", placeholder: "Grupo 1, Grupo 2" %>

  <%= f.text_field :ticket_link, label: "Link a compra del ticket:" %>

  <br><%= f.hidden_field :admin_id, :value => current_admin.id %>
  <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<script type="text/javascript">

   $(document).ready(function(){
   // var q="System of down";
    $("#myCarousel").find(" .carousel-indicators >li").each(function(index,el){ 
        var $el = $(el);
      if(index == 0)
        mostrarCaratula($(el).attr("data-nombre"),"active");
      else 
        mostrarCaratula($(el).attr("data-nombre"),""); 
        });
    
       function mostrarCaratula(nombre,active){

        $.get('https://api.spotify.com/v1/search?q='+nombre+'&type=artist',function(data){
        var imagenes = data.artists.items[0].images;
        var html="";
      html ='<div class="item '+active+'"><img src="'+imagenes[0].url+'" alt="'+nombre+'" width="460" height="345"   class="img-rounded"></div>'
        $("#myCarousel").find(".carousel-inner").append(html);
            });
       }
     
      });
         
  </script> 
  <style type="text/css">
  .content:before {
  content: "";
  position: fixed;
  left: 0;
  right: 0;
  z-index: -1;
  
  display: block;
  background-image: url('http://666a658c624a3c03a6b2-25cda059d975d2f318c03e90bcf17c40.r92.cf1.rackcdn.com/unsplash_527bf56961712_1.JPG');
  width: 1200px;
  height: 800px;
  
  -webkit-filter: blur(5px);
  -moz-filter: blur(5px);
  -o-filter: blur(5px);
  -ms-filter: blur(5px);
  filter: blur(5px);
}

.content {
  position: fixed;
  left: 0;
  right: 0;
  z-index: 0;
  margin-left: 20px;
  margin-right: 20px;
}
</style>

<div class="content">
<div class="row">
  <div class="col-md-12">
    <div class="jumbotron">
      <h1><%= @event.name %></h1>
      <p><%=  @event.description %></p>
    </div>
  </div>
</div>

<div class="col-md-4">
</div>

<div class="col-md-4">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
    <!--li data-target="#myCarousel" data-slide-to="0" data-nombre="Chancho en piedra" class="active"></li-->
    <% @event_artists.each do | ar | %>
      <li data-target="#myCarousel" data-slide-to="0" data-nombre="<%= ar %>" ></li>
      
    <% end %>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <!--div class="item ">
        <img src="img_flower2.jpg" alt="Flower" width="460" height="345">
      </div-->
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

<div class="col-md-4">
  <div role="tabpanel">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Evento</a></li>
      <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Artistas</a></li>
      <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Entradas</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="home">
      	<%=  @event.description %>
      </div>
      <div role="tabpanel" class="tab-pane" id="profile">Lista de los artistas</div>
      <div role="tabpanel" class="tab-pane" id="messages">
      	<ul class="list-group">
          <li class="list-group-item"><%= link_to 'Comprar Primera Fila', @event.ticket_link %> <span class="badge">$75</span></li>
          <li class="list-group-item"><%= link_to 'Comprar Segunda Fila', @event.ticket_link %> <span class="badge">$75</span></li>        
          <li class="list-group-item"><%= link_to 'Compra Platea Baja', @event.ticket_link %><span class="badge">$75</span></li>
          <li class="list-group-item"><%= link_to 'Comprar Tribuna', @event.ticket_link %><span class="badge">$75</span></li>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.erb
<footer	class="footer">
		<small>
				© 2015 Bidah, Canas, Waflessnet
				<!--
				The	<a	href="http://www.railstutorial.org/">Ruby	on	Rails	Tutorial</a>
				by	<a	href="http://www.michaelhartl.com/">Michael	Hartl</a>
				-->
		</small>
		<nav>
				<ul>
						<li><%=	link_to	"¿Qué es Festify?",	about_path	%></li>
						<li><%=	link_to	"Contacto",	contact_path	%></li>
						<!--<li><a	href="http://news.railstutorial.org/">News</a></li>-->
				</ul>
		</nav>
</footer>

app/views/layouts/_header.html.erb
<header	class="navbar	navbar-fixed-top	navbar-inverse">
			<span id="logo">
				<!-- <span style="color:#FFAC0D">FESTI</span>FY<i class="fa fa-spotify fa-lv"></i> -->
				<%= link_to image_tag('logo_fondo_transparente_con_blanco.png', style: 'max-width:70%'),root_path %>
			</span>

			<nav>
					<ul	class="nav	navbar-nav	navbar-right logo">

							<li><%=	link_to	"Login",	"home/index"	%></li>
					</ul>
			</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if	lt	IE	9]>
						<script	src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
						</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE	html>
<html>
		<head>
				<title>Festify</title>
				<%=	stylesheet_link_tag	'application',	media:	'all', 'data-turbolinks-track'	=>	true	%>
				<%=	javascript_include_tag	'application',	'data-turbolinks-track'	=>	true	%>
				<%=	csrf_meta_tags	%>
				<%= render 'layouts/shim' %>
				<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="http://bootswatch.com/cyborg/bootstrap.min.css"> 
			  
		</head>
		<body>
		<div class="container">
				<p class="notice"><%= notice %></p>
				<p class="alert"><%= alert %></p>
				<%= render 'layouts/header' %>
				<div	class="container">
						<%=	yield	%>
						<%= render 'layouts/footer' %>
				</div>
		</div>
		</body>
</html>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>